config/routes.rb
Rails.application.routes.draw do

  get 'search/box'
  get 'search/results'

  get 'home/index'
  get 'home_controller/index'

  get 'shops/show'
  get 'shops/location'
  get 'shops/comments'

  get 'users/using'
  get 'users/used'

  get 'products/overview'
  get 'products/comments'
  get 'products/shops'

  get 'brands/show'

  [*1..6].each do |i|

    get "brands/alt" + i.to_s

  end

  # get 'brands/alt1'
  # get 'brands/alt2'
  # get 'brands/alt3'
  # get 'brands/alt4'
  # get 'brands/alt5'
  # get 'brands/alt6'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def show
  end

  def alt1
  end

  def alt2
  end

  def alt3
  end

  def alt4
  end

  def alt5
  end

  def alt6
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def comments
  end

  def shops
  end

  def overview
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def box
  end

  def results
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def show
  end

  def location
  end

  def comments
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def using
  end

  def used
  end
end

app/helpers/application_helper.rb
require 'uri'

module ApplicationHelper

  def placeholder width = 100, height = 100, bg_color: '#CCC', text_color: "#888" 
    data_uri = "data:image/svg+xml;charset=utf-8,"

    svg_string = %Q(
      <svg xmlns='http://www.w3.org/2000/svg' width='#{width}' height='#{height}'>
        <rect width='100%' height='100%' fill='#{bg_color}' />
        <text x='#{width/2}' y='#{height/2+((width+height)/36)}' font-family="sans-serif" font-size='#{(width+height)/18}' fill='#{text_color}' text-anchor='middle'>
          #{width} x #{height}
        </text>
      </svg>
    )

    data_uri += URI.escape(svg_string)

    data_uri
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-dark navbar-full bg-inverse">
  <%= link_to "Site", root_path, class: 'navbar-brand' %>

  <ul class="nav navbar-nav">
    <li class="nav-item">
      <%= link_to 'Brand', brands_show_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Product', products_overview_path, class: 'nav-link'  %>
    </li>
    <li class="nav-item">
      <%= link_to 'User', users_using_path, class: 'nav-link'  %>
    </li>
    <li class="nav-item">
      <%= link_to 'Shop', shops_show_path, class: 'nav-link'  %>
    </li>

  </ul>

  <ul class="nav navbar-nav float-xs-right">
    <li class="nav-item">
      <a href="#" class="nav-link">Country</a>
    </li>

  </ul>

</nav>

app/views/brands/_tabs.html.erb
<div class="bb-1" style="margin: 0 -30px; padding: 0 30px">
  <ul class="nav nav-tabs mt-3" style="position: relative; margin-bottom: -1px">
    <li class='nav-item'>
      <%= link_to_unless_current 'Products', brands_show_path, class: 'nav-link' do %>
        <%= link_to 'Products', brands_show_path, class: 'nav-link active' %>
      <% end %>
    </li>

  </ul>
  
</div>

app/views/brands/_title.html.erb
<div class="row">
  <div class="col-sm-2">
    <%= image_tag "vestel-logo-red", class: 'figure-img img-fluid rounded img-thumbnail' %>
  </div>
  <div class="col-sm-10">
    <h1 class="h3 mt-1">Vestel</h1>
    <ul class="nav nav-inline dot-spacer text-muted">
      <li class="nav-item"><a href="#">Elektronics</a></li>
    </ul>
  </div>
  
</div>

app/views/brands/show.html.erb
<%= render 'navbar' %>

<div class="container py-5 px-5 bg-white rounded mt-3">

  <%= render 'title' %>

  <%= render 'tabs' %>


  <div class="mt-2">


    <div class="row">
      <div class="col-sm-3 category-title">TVs</div>
      <div class="col-sm-9">
        <a href="#">No Frost</a>, 
        <a href="#">Frost</a>, 
        <a href="#">Buro Type</a>, 
        <a href="#">Two Doored Type</a>, 
        <a href="#">Single Doored Type</a>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3 category-title">Refrigerators</div>
      <div class="col-sm-9">
        <a href="#">Led TV</a>, 
        <a href="#">4K UHD</a>, 
        <a href="#">OLED LEd TV</a>, 
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3 category-title">Washing Machines</div>
      <div class="col-sm-9">
        <a href="#">Washing Machines</a>,
        <a href="#">Washing Machines with Drying</a>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3 category-title">TVs</div>
      <div class="col-sm-9">
        <a href="#">No Frost</a>, 
        <a href="#">Frost</a>, 
        <a href="#">Buro Type</a>, 
        <a href="#">Two Doored Type</a>, 
        <a href="#">Single Doored Type</a>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3 category-title">Refrigerators</div>
      <div class="col-sm-9">
        <a href="#">Led TV</a>, 
        <a href="#">4K UHD</a>, 
        <a href="#">OLED LEd TV</a>, 
        <a href="#">Led TV</a>, 
        <a href="#">4K UHD</a>, 
        <a href="#">OLED LEd TV</a>, 
        <a href="#">Led TV</a>, 
        <a href="#">4K UHD</a>, 
        <a href="#">OLED LEd TV</a>, 
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3 category-title">Washing Machines</div>
      <div class="col-sm-9">
        <a href="#">Washing Machines</a>,
        <a href="#">Washing Machines with Drying</a>
      </div>
    </div>
          
  </div>
</div>

app/views/home/index.html.erb
<style type="text/css">
html, body, #a {
  margin: 0;
  padding: 0;
  height: 100%;
  width: 100%;
}

#a {
  display: table;
}

#b {
  display: table-cell;
  margin: 0;
  padding: 0;

  text-align: center;
  vertical-align: middle;
}

#content {
  margin: auto;
}
</style>

<div id="a">
  <div id="b">
    <div id="content">
      <div class="row">
        <div class="col-sm-6 offset-sm-3">
          <form action="<%= search_box_path %>" method="get">
            <input class="form-control form-control-lg" type="text" id="search" value='galaxy' placeholder="Product, brand or shop" autofocus>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var searchInput = document.getElementById('search');
  var strLen = searchInput.value.length;
  searchInput.setSelectionRange(strLen, strLen); 
</script> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Sketch</title>
    <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_tabs.html.erb
<div class="bb-1">
  <ul class="nav nav-tabs mt-3" style="position: relative; margin-bottom: -1px">
    <li class='nav-item'>
      <%= link_to_unless_current 'Overview', products_overview_path, class: 'nav-link' do %>
        <%= link_to 'Overview', products_overview_path, class: 'nav-link active' %>
      <% end %>
    </li>
    <li class='nav-item'>
      <%= link_to_unless_current '21 shops', products_shops_path, class: 'nav-link' do %>
        <%= link_to '21 shops', products_shops_path, class: 'nav-link active' %>
      <% end %>
    </li>
    <li class='nav-item'>
      <%= link_to_unless_current '567 comments', products_comments_path, class: 'nav-link' do %>
        <%= link_to '567 comments', products_comments_path, class: 'nav-link active' %>
      <% end %>
    </li>
    <li class='nav-item'>
      <a class="nav-link">12234 using</a>
    </li>
    <li class='nav-item'>
      <a class="nav-link">21078 used</a>
    </li>



    <li class="nav-item dropdown float-xs-right">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <%= image_tag "icons/more" %>
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Forum</a>
        <a class="dropdown-item" href="#">Medias</a>
        <a class="dropdown-item" href="#">Specifications</a>
        <a class="dropdown-item" href="#">Popularity</a>
        <a class="dropdown-item" href="#">Generations</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Support</a>
      </div>
    </li>

  </ul>
  
</div>

app/views/products/_title.html.erb
<div class="row">
  <div class="col-sm-2">
    <%= image_tag placeholder(150, 150), class: 'figure-img img-fluid rounded' %>
  </div>
  <div class="col-sm-10">
    <h1 class="h3 mt-1">Galaxy S5</h1>
    <ul class="nav nav-inline dot-spacer text-muted">
      <li class="nav-item"><a href="#" data-toggle="modal" data-target="#myModal">by Samsung</a></li>
      <li class="nav-item"><a href="#">Android Phones</a></li>
      <li class="nav-item">production and selling</li>
    </ul>
  </div>
  
</div>




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Mobile Phones from Samsung</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "http://placehold.it/300x300.png", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">A caption for the above image.</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "http://placehold.it/300x300.png", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">A caption for the above image.</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "http://placehold.it/300x300.png", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">A caption for the above image.</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "http://placehold.it/300x300.png", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">A caption for the above image.</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "http://placehold.it/300x300.png", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">A caption for the above image.</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "http://placehold.it/300x300.png", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">A caption for the above image.</a>
              </figcaption>
            </figure>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/comments.html.erb
<%= render 'navbar' %>

<div class="container py-5 px-5 bg-white mt-3 rounded">
  <div class="row">

    <div class="col-sm-12">

      <%= render 'title' %>

      <%= render 'tabs' %>
 
      <div class="comments mt-2">

        <% ['jack', 'angelina', 'julia', 'mao', 'marie', 'minna', 'paul'].shuffle.each do |user| %>

          <div class="row py-1">
            <div class="col-sm-2">
              <%= image_tag "users/" + user, class: 'rounded-circle w-100' %>
            </div>
            <div class="col-sm-10">
              <div>
                <span class="font-weight-bold"><%= Faker::Name.name %></span>
                said
                <span class="font-weight-bold">
                  <%= rand(15..30) %>
                  <%= ['minutes', 'hours', 'days', 'months'][rand(0..3)] %>
                  ago:
                </span>
              </div>
              <% Faker::Lorem.paragraphs(rand 1..4  ).each do |p| %>
                <p><%= p %><p>
              <% end %>
            </div>
          </div>
        
        <% end %>

      </div>


    </div>
  </div>
</div>

app/views/products/shops.html.erb
<%= render 'navbar' %>

<div class="container py-5 px-5 bg-white rounded mt-3">

  <%= render 'title' %>

  <%= render 'tabs' %>


  <div class="mt-2">

    <div class="pb-1 mb-1 bb-1">
      <nav class="nav nav-inline">
        <span class="nav-link">Sort By:</span>
        <a class="nav-link" href="#">Optimal</a>
        <a class="nav-link" href="#">Shop Popularity</a>
        <span class="nav-link active" href="#">Price</span>
      </nav>
    </div>


    <% 21.times do %>
      <div class="row py-1 shop-item">
        
        <div class="col-sm-1">
          <%= image_tag ['shop', 'shop1'].shuffle.first, class: "w-100" %> 
        </div>

        <div class="col-sm-6">
          <h3 class="h6"><%= Faker::Company.name %></h3>
          <div><a href="#">Samsung Galaxy S5</a></div>
        </div>

        <div class="col-sm-5 text-xs-right">
          <span class="price">$<%= Faker::Number.between(700, 800) %></span>
        </div>

      </div>
    <% end %>





  </div>

</div>

app/views/search/box.html.erb
<%= render 'navbar' %>


<div class="container mt-3">
  <div class="row">
    <form action="<%= search_results_path %>" method="get">
      <input class="form-control form-control-lg px-5" type="text" id='search' value='galaxy' placeholder="Product, brand or shop" autofocus>
    </form>
  </div>
</div>

<script type="text/javascript">
  
  var searchInput = document.getElementById('search');
  var strLen = searchInput.value.length;
  searchInput.setSelectionRange(strLen, strLen); 

</script>



<div class="container px-5 bg-white rounded">
  
  <a href="<%= search_results_path %>" class="py-05 bb-1 d-block text-gray-dark mp-50 hover-color-faded">
    galaxy note 7
  </a>

  <a href="<%= search_results_path %>" class="py-05 bb-1 d-block text-gray-dark mp-50 hover-color-faded">
    galaxy s7 
  </a>

  <a href="<%= search_results_path %>" class="py-05 bb-1 d-block text-gray-dark mp-50 hover-color-faded">
    galaxy s7 
  </a>

  <a href="<%= search_results_path %>" class="py-05 bb-1 d-block text-gray-dark mp-50 hover-color-faded">
    galaxy j7 
  </a>

  <a href="<%= search_results_path %>" class="py-05 bb-1 d-block text-gray-dark mp-50 hover-color-faded">
    galaxy s7 edge 
  </a>
    
</div>

app/views/search/results.html.erb
<%= render 'navbar' %>


<div class="container mt-3">
  <div class="row">
    <input class="form-control form-control-lg px-5" type="text" id='search' value='galaxy' placeholder="Product, brand or shop" autofocus>
    </div>
</div>

<script type="text/javascript">
  
  var searchInput = document.getElementById('search');
  var strLen = searchInput.value.length;
  searchInput.setSelectionRange(strLen, strLen); 

</script>

<div class="container py-5 px-5 bg-white rounded mt-1">
  <h2 class="h5 bb-1 pb-1 mb-3 text-muted">Search Results</h2>


  <h3 class="h6 bb-1 mb-1 pb-1 text-muted">PRODUCTS</h3>
  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy S5</a></div>
      Mobile Phone by Samsung
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy S7</a></div>
      Mobile Phone by Samsung
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy S7 Edge</a></div>
      Mobile Phone by Samsung
    </div>
  </div>
  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy S6</a></div>
      Mobile Phone by Samsung
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy A1</a></div>
      Mobile Phone by Samsung
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy A3</a></div>
      Mobile Phone by Samsung
    </div>
  </div>
  <div class="text-xs-right"><a href="#">more</a></div>







  <h3 class="h6 bb-1 mb-1 mt-3 pb-1 text-muted">SHOPS</h3>
  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaksi Computer</a></div>
      Kucukcekmece, Istanbul
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy Healtcare</a></div>
      galaxyhealtcare.com
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy Schools</a></div>
      St. Blvrd, San Francisco
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxies Gamers</a></div>
      galaxies-gamers.com
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxxy Cafe</a></div>
      Rome, Italy
    </div>
  </div>

  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div><a href="#">Galaxy Schools</a></div>
      St. Blvrd, San Francisco
    </div>
  </div>
  <div class="text-xs-right"><a href="#">more...</a></div>


  <h3 class="h6 bb-1 mb-1 mt-3 pb-1 text-muted">BRANDS</h3>
  <div class="row mb-1">
    <div class="col-xs-1">
      <%= image_tag placeholder(50, 50), class: 'img-fluid' %>  
    </div>

    <div class="col-xs-9">
      <div>Galaksi</div>
      <a href="#">Dry Cleaneing Services</a>
    </div>
  </div>

</div>

app/views/shops/_tabs.html.erb
<div class="tabs mt-3">
  <ul class="nav nav-tabs">
    <li class='nav-item'>
      <%= link_to_unless_current 'Products', shops_show_path, class: 'nav-link' do %>
        <%= link_to 'Products', shops_show_path, class: 'nav-link active' %>
      <% end %>
    </li>
    <li class='nav-item'>
      <%= link_to_unless_current 'Location', shops_location_path, class: 'nav-link' do %>
        <%= link_to 'Location', shops_location_path, class: 'nav-link active' %>
      <% end %>
    </li>
    <li class='nav-item'>
      <%= link_to_unless_current 'Comments', shops_comments_path, class: 'nav-link' do %>
        <%= link_to 'Comments', shops_comments_path, class: 'nav-link active' %>
      <% end %>
    </li>


  </ul>
</div>

app/views/users/_tabs.html.erb
<div class="tabs mt-3">
  <ul class="nav nav-tabs">
    <li class='nav-item'>
      <%= link_to_unless_current 'Using', users_using_path, class: 'nav-link' do %>
        <%= link_to 'Using', users_using_path, class: 'nav-link active' %>
      <% end %>
    </li>

    <li class='nav-item'>
      <%= link_to_unless_current 'Used', users_used_path, class: 'nav-link' do %>
        <%= link_to 'Used', users_used_path, class: 'nav-link active' %>
      <% end %>
    </li>
  </ul>
</div>

app/views/users/using.html.erb
<%= render 'navbar' %>

<div class="container py-5 px-5 bg-white rounded mt-3">
  <div class="row">

    <div class="col-sm-12">

      <%= render 'title' %>

      <%= render 'tabs' %>
 
      <div class="comments mt-2">

        <div class="row">
          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag 'mys/galaxy-s5', class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <%= link_to 'Samsung Galaxy S5', products_overview_path %>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/kangoo-15-dci", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">Renault Kangoo 1.5 dCi</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/xps-13", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">Dell Xps 13</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/m187", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">Logitech M187</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/toki-konutlari", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">Kayasehir Toki Konutlari</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/flatron-w2243s", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">LG Flatron W2243S</a>
              </figcaption>
            </figure>
          </div>


          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/mouse-3000", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">Microsoft Mouse 3000</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/puzzi-101", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">Karcher Puzzi 10/1</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-4 mb-1">
            <figure class="figure">
              <%= image_tag "mys/sphera-30", class: 'w-100 figure-img img-fluid rounded' %>
              <figcaption class="figure-caption">
                <a href="#">Bosch Sphera 30</a>
              </figcaption>
            </figure>
          </div>

          <div class="col-sm-12">
            <div class="card">
              <a class="d-block py-1 text-xs-center" href="#">more...</a>
            </div>
          </div>
        </div>

      </div>


    </div>
  </div>
</div>